apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello
  name: hello
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: hello
  type: NodePort
